---
- name: clear facts play
  hosts: hcloud
  remote_user: "{{ users | json_query('[*].name') | first }}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{{ ssh_port }}"
  become: no
  gather_facts: no
  tasks:
    - name: clear gathered facts from all currently targeted hosts
      ansible.builtin.meta: clear_facts
