---
- name: connection play
  hosts: hcloud
  ignore_unreachable: yes
  remote_user: "{% if hostvars['localhost']['server'].changed %}root{% else %}{{ users | json_query('[*].name') | first }}{% endif %}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{% if hostvars['localhost']['server'].changed %}22{% else %}{{ ssh_port }}{% endif %}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: wait 40 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        timeout: 40
  roles:
    - users
    - sudo
    - ssh
  post_tasks:
    - name: bring host(-s) back to play after failure (e.g., if one host was unreachable)
      ansible.builtin.meta: clear_host_errors
