---
- name: connection play
  hosts: hcloud
  ignore_unreachable: yes
  remote_user: "{% if hostvars['localhost']['server'].changed %}root{% else %}{{ users | json_query('[*].name') | first }}{% endif %}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{% if hostvars['localhost']['server'].changed %}22{% else %}{{ ssh_port }}{% endif %}"
  become: yes
  gather_facts: no
  roles:
    - connection
