---
- hosts:
    - all
  remote_user: "{{ users | json_query('[*].name') | first }}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{{ ssh_port }}"
  become: no
  gather_facts: yes
  tasks:
    - name: try to connect to host
      ansible.builtin.ping:
    - name: print all available facts
      ansible.builtin.debug:
        var: ansible_facts
