---
- name: bootstrap play
  hosts:
    - centos-2gb-hel1-1
  ignore_unreachable: yes
  remote_user: root
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  become: yes
  gather_facts: yes
  roles:
    - base

- name: ping play
  hosts:
    - centos-2gb-hel1-1
  remote_user: "{{ users | json_query('[*].name') | first }}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{{ ssh_port }}"
  become: yes
  gather_facts: yes
  roles:
    - base
  tasks:
    - ansible.builtin.ping:
