---
- name: include a play to create a basic ssh key and a server with ssh key
  import_playbook: resources.yml

- name: include a play to create users and configure ssh; performed after the previous play, depends on it
  import_playbook: connection.yml

- name: include a play to configure server security; performed after the previous two plays, doesn't depend on them
  import_playbook: security.yml

- name: include a play to configure common basic settings
  import_playbook: base.yml
