---
- name: resources play
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    hcloud_token: "{{ vault_hcloud_token }}"
  roles:
    - resources

- name: bootstrap play
  hosts: centos-2gb-hel1-1
  remote_user: "{% if hostvars['localhost']['server'].changed %}root{% else %}{{ users | json_query('[*].name') | first }}{% endif %}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: "{% if hostvars['localhost']['server'].changed %}22{% else %}{{ ssh_port }}{% endif %}"
  become: yes
  gather_facts: no
  roles:
    - base
