---
- name: check installed version
  ansible.builtin.command:
    cmd: op --version
  register: current_version
  delegate_to: localhost
  failed_when: false
  changed_when: false

- name: if the tool isn't installed, then set the version to zero; otherwise, set the current version
  ansible.builtin.set_fact:
    current_version: "{% if current_version.failed %}0{% else %}{{ current_version.stdout }}{% endif %}"

- name: download the tool
  ansible.builtin.unarchive:
    src: https://cache.agilebits.com/dist/1P/op/pkg/v{{ one_password_cli_version }}/op_linux_amd64_v{{ one_password_cli_version }}.zip
    dest: /usr/local/bin
    remote_src: yes
  when: "'{{ one_password_cli_version }}' != '{{ current_version }}'"
  delegate_to: localhost

- name: delete .sig file included in the download
  ansible.builtin.file:
    path: /usr/local/bin/op.sig
    state: absent
  delegate_to: localhost
