---
servers:
  - name: kube-hel1-htz-1
    group:
      - kube-master
      - etcd
    ip: 10.0.0.3
    etcd_member_name: etcd1
  - name: kube-hel1-htz-2
    group:
      - kube-master
      - etcd
    ip: 10.0.0.4
    etcd_member_name: etcd2
  - name: kube-hel1-htz-3
    group:
      - kube-master
      - etcd
    ip: 10.0.0.5
    etcd_member_name: etcd3
  - name: kube-hel1-htz-4
    group:
      - kube-node
    ip: 10.0.0.6
  - name: kube-hel1-htz-5
    group:
      - kube-node
    ip: 10.0.0.7

users:
  - name:     "{{ vault_name }}"
    comment:  "{{ vault_comment }}"
    password: "{{ vault_password }}"
  - name:     example_user
    comment:  Example User
    password: "eBhPUgKd9J,&9}]D4Wq*~#wb"
  - name:     sample_user
    comment:  Sample User
    password: "Jus&=3ci.Kcm?HzxAJzAGjd8"

ssh_port: "{{ vault_ssh_port }}"

one_password_cli_version:     1.8.0
one_password_device_id:       "{{ vault_one_password_device_id }}"
one_password_master_password: "{{ vault_one_password_master_password }}"
one_password_subdomain:       "{{ vault_one_password_subdomain }}"
one_password_email_address:   "{{ vault_one_password_email_address }}"
one_password_secret_key:      "{{ vault_one_password_secret_key }}"
one_password_vault_name:      "{{ vault_one_password_vault_name }}"

git_version: 2.31.1

github_username: "{{ vault_github_username }}"
github_password: "{{ vault_github_password }}"
