---
network: 10.0.0.0/16
subnetwork: 10.0.0.0/24

load_balancers:
  - name: load-balancer-1
    ip: 10.0.0.2

servers:
  - name: kube-hel1-htz-1
    type: cx11
    image: centos-stream-8
    group:
      - kube-master
      - etcd
    ip: 10.0.0.3
    etcd_member_name: etcd1
  - name: kube-hel1-htz-2
    type: cx11
    image: centos-stream-8
    group:
      - kube-master
      - etcd
    ip: 10.0.0.4
    etcd_member_name: etcd2
  - name: kube-hel1-htz-3
    type: cx11
    image: centos-stream-8
    group:
      - kube-master
      - etcd
    ip: 10.0.0.5
    etcd_member_name: etcd3
  - name: kube-hel1-htz-4
    type: cx11
    image: centos-stream-8
    group:
      - kube-node
    ip: 10.0.0.6
  - name: kube-hel1-htz-5
    type: cx11
    image: centos-stream-8
    group:
      - kube-node
    ip: 10.0.0.7

users:
  - name:    "{{ vault_name }}"
    comment: "{{ vault_comment }}"
  - name:    example_user
    comment: Example user
  - name:    sample_user
    comment: Sample user
