---
servers:
  - name: centos-2gb-hel1-1
#  - name: centos-2gb-hel1-2
#  - name: centos-2gb-hel1-3

users:
  - name: "{{ vault_name }}"
    comment: "{{ vault_comment }}"
    password: "{{ vault_password }}"
#  - name: example_user
#    comment: Example User
#    password: hUnvYXeyeywnr8xKECVfjxF8

ssh_port: "{{ vault_ssh_port }}"

one_password_device_id: "{{ vault_one_password_device_id }}"
one_password_password: "{{ vault_one_password_password }}"
one_password_sign_in_address: "{{ vault_one_password_sign_in_address }}"
one_password_email_address: "{{ vault_one_password_email_address }}"
one_password_secret_key: "{{ vault_one_password_secret_key }}"
one_password_vault_name: "{{ vault_one_password_vault_name }}"
