---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt will use this email address to contact you about expiring
    # certificates, and issues related to your account.
    email: "{{ vault_letsencrypt_email }}"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "{{ vault_letsencrypt_email }}"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt will use this email address to contact you about expiring
    # certificates, and issues related to your account.
    email: "{{ vault_letsencrypt_email }}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-production-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "{{ vault_letsencrypt_email }}"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
