---
- name: check installed version
  ansible.builtin.shell:
    cmd: kubectl version --client | awk -F "GitVersion:\"" '{print$2}' | awk -F "\"" '{print$1}'
  register: current_version
  ignore_errors: true
  changed_when: false

- name: if the tool isn't installed, then set the version to zero; otherwise, set the current version
  ansible.builtin.set_fact:
    current_version: "{% if 'not found' in current_version.stderr %}0{% else %}{{ current_version.stdout }}{% endif %}"

- name: check stable version
  ansible.builtin.shell:
    cmd: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
  register: stable_version
  changed_when: false

- name: download latest version of kubectl
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ stable_version.stdout }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: yes
  when: "'{{ stable_version.stdout }}' != '{{ current_version }}'"
  become: yes

- name: create a directory for kube configs
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: '0750'
