---
- name: install the software that git depends on
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gettext-devel
      - openssl-devel
      - perl-CPAN
      - perl-devel
      - zlib-devel
      - gcc
      - autoconf
      - libcurl-devel
      - expat-devel

- name: check installed version
  ansible.builtin.command:
    argv:
      - /usr/local/bin/git
      - --version
  register: git_installed_version
  changed_when: false
  ignore_errors: true

- name: if git isn't installed, then set the version to zero; otherwise, set the current version
  ansible.builtin.set_fact:
    installed_version: "{% if git_installed_version.failed %}0{% else %}{{ git_installed_version.stdout[12:] }}{% endif %}"

- name: build git
  block:
    - name: download git tarball
      ansible.builtin.unarchive:
        src: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz
        dest: /usr/local/src/
        remote_src: yes

    - name: declare the appropriate destination for the binary and compile the source code into a working program
      ansible.builtin.command:
        argv:
          - make
          - prefix=/usr/local
          - all
        chdir: /usr/local/src/git-{{ git_version }}/
        creates: /usr/local/src/git-{{ git_version }}/git

    - name: install git
      ansible.builtin.command:
        argv:
          - make
          - prefix=/usr/local
          - install
        chdir: /usr/local/src/git-{{ git_version }}/
  when: "'{{ git_version }}' != '{{ installed_version }}'"
