---
# ------------------- server ------------------- #
- name: create a ssh key
  hetzner.hcloud.hcloud_ssh_key:
    api_token: "{{ hcloud_token }}"
    name: "{{ users | json_query('[*].name') | first }}"
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: create a network
  hetzner.hcloud.hcloud_network:
    api_token: "{{ hcloud_token }}"
    name: network-1
    ip_range: 10.0.0.0/16

- name: create a subnetwork
  hetzner.hcloud.hcloud_subnetwork:
    api_token: "{{ hcloud_token }}"
    network: network-1
    ip_range: 10.0.0.0/24
    network_zone: eu-central
    type: cloud

- name: create a server with ssh key
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ item.name }}"
    server_type: cx11
    image: centos-8
    location: hel1
    ssh_keys: [ "{{ users | json_query('[*].name') | first }}" ]
  loop: "{{ servers }}"
  register: server

- name: create a server network and specify the ip address
  hetzner.hcloud.hcloud_server_network:
    api_token: "{{ hcloud_token }}"
    network: network-1
    server: "{{ item.name }}"
    ip: "{{ item.ip }}"
  loop: "{{ servers }}"

# ------------------- load balancer ------------------- #
- name: create a load balancer
  hetzner.hcloud.hcloud_load_balancer:
    api_token: "{{ hcloud_token }}"
    name: load-balancer-1
    location: hel1
    load_balancer_type: lb11

- name: create a load balancer network and specify the ip address
  hetzner.hcloud.hcloud_load_balancer_network:
    api_token: "{{ hcloud_token }}"
    load_balancer: load-balancer-1
    network: network-1
    ip: 10.0.0.2

- name: add host to group 'kube-node'
  ansible.builtin.add_host:
    name: "{{ item.name }}"
    groups: kube-node
  when: "'kube-node' in {{ item.group }}"
  loop: "{{ servers }}"
  changed_when: false

- name: create a server load balancer target
  hetzner.hcloud.hcloud_load_balancer_target:
    api_token: "{{ hcloud_token }}"
    load_balancer: load-balancer-1
    type: server
    server: "{{ item }}"
    use_private_ip: yes
  loop: "{{ groups['kube-node'] }}"

- name: create a load balancer service (1/2)
  hetzner.hcloud.hcloud_load_balancer_service:
    api_token: "{{ hcloud_token }}"
    load_balancer: load-balancer-1
    protocol: http
    listen_port: 80

- name: create a load balancer service (2/2)
  hetzner.hcloud.hcloud_load_balancer_service:
    api_token: "{{ hcloud_token }}"
    load_balancer: load-balancer-1
    listen_port: 80
    health_check:
      http:
        path: "/healthz"
  changed_when: false

# ------------------- folders and files ------------------- #
- name: create folders for inventory and group variables
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - inventory
    - group_vars/hcloud

- name: create a hetzner cloud dynamic inventory file
  ansible.builtin.blockinfile:
    path: inventory/hcloud.yml
    block: |
      ---
      plugin: hcloud
      token: {{ vault_hcloud_token }}
    create: yes

- name: create a symbolic links from host vars to group vars
  ansible.builtin.file:
    src: "{{ playbook_dir }}/host_vars/localhost/{{ item }}.yml"
    dest: "{{ playbook_dir }}/group_vars/hcloud/{{ item }}.yml"
    state: link
  loop:
    - vars
    - vault
