---
- name: delete item(-s) in 1password
  block:
    - name: sign in to a 1password account
      ansible.builtin.shell:
        cmd: |
          export OP_DEVICE="{{ one_password_device_id }}"
          echo "{{ one_password_master_password }}" | op signin "{{ one_password_subdomain }}.1password.com" "{{ one_password_email_address }}" "{{ one_password_secret_key }}" --raw
      register: op_session_token
      changed_when: false

    - name: delete item(-s)
      ansible.builtin.shell:
        cmd: |
          export "OP_SESSION_{{ one_password_subdomain }}"="{{ op_session_token.stdout }}"
          op delete item "{{ item.name }}" --vault "{{ one_password_vault_name }}"
      loop: "{{ servers }}"
      ignore_errors: true
      no_log: true
      changed_when: false

    - name: sign out from a 1password account (1/2)
      ansible.builtin.shell:
        cmd: op signout --forget
      changed_when: false

    - name: sign out from a 1password account (2/2)
      ansible.builtin.file:
        path: $HOME/.config/op/config
        state: absent
  run_once: true

- name: delete directories for group variables and inventory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - group_vars
    - inventory

- name: delete a server
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ servers }}"

- name: delete a basic network
  hetzner.hcloud.hcloud_network:
    api_token: "{{ hcloud_token }}"
    name: network-1
    state: absent

- name: delete a basic ssh_key
  hetzner.hcloud.hcloud_ssh_key:
    api_token: "{{ hcloud_token }}"
    name: "{{ users | json_query('[*].name') | first }}"
    state: absent
