---
- name: include tasks to create server(-s), inventory and variables
  ansible.builtin.import_tasks: create.yml

- name: include tasks to delete all created resources during playbooks execution
  ansible.builtin.import_tasks: destroy.yml
  tags: [ never, destroy ]

- name: refresh inventory to ensure instances exist in (or removed from) inventory
  ansible.builtin.meta: refresh_inventory
