---
- name: add user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: wheel
    append: yes
  loop: "{{ users }}"
  changed_when: False
  no_log: true

- name: set authorized key
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop: "{{ users }}"
  no_log: true
