---
- name: install package which allows restricting a package to a fixed version number
  ansible.builtin.dnf:
    name: python3-dnf-plugin-versionlock

- name: lock the docker version
  ansible.builtin.blockinfile:
    path: /etc/dnf/plugins/versionlock.list
    block: |
      docker-ce-3:19.03.14-3.el8.*
      docker-ce-cli-1:19.03.14-3.el8.*

- name: set up the stable repository
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - --add-repo
      - https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo

- name: install the docker engine and containerd
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: start and enable service docker
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes

- name: manage docker as a non-root user
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  loop: "{{ users }}"
  no_log: true

- name: configure the default logging driver
  ansible.builtin.copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    dest: /etc/docker/daemon.json
  notify: restart docker
